### ISSUE TITLE
Error while running single_image_object_counting.py

### ISSUE THREAD

**Issue by jiansheng77** [ahmetozlu/tensorflow_object_counting_api#22]
Hi. I am trying to run the single_image_object_counting.py file but i keep running into Runtimeerror: Attempted to use a closed session. 

I saw the other threads and tried changing the object detection api file but it didnt work as well. I am trying to count the number of dogs and cats using my own test data. 

Traceback (most recent call last):
  File "C:\tensorflow1\model\research\object_detection\single_image_object_counting.py", line 26, in <module>
    result = object_counting_api.single_image_object_counting(input_video, detection_graph, category_index, is_color_recognition_enabled, fps, width, height) # targeted objects counting
  File "C:\tensorflow1\model\research\object_detection\api\object_counting_api.py", line 475, in single_image_object_counting
    counter, csv_line, counting_mode = vis_util.visualize_boxes_and_labels_on_single_image_array(1,input_frame,
AttributeError: module 'utils.visualization_utils' has no attribute 'visualize_boxes_and_labels_on_single_image_array'

Can you help me please

**Comment by zazizou** [comment]
Hi,

I am actually struggling with similar issues with single_image_object_counting.py. I did not change the default file.

Here are my logs

Traceback (most recent call last):
  File "single_image_object_counting.py", line 27, in <module>
    result = object_counting_api.single_image_object_counting(input_video, detection_graph, category_index, is_color_recognition_enabled, fps, width, height) # targeted objects counting
  File "/home/momo/WorkSpace/tensorflow_object_counting_api/api/object_counting_api.py", line 471, in single_image_object_counting
    feed_dict={image_tensor: image_np_expanded})
  File "/home/momo/.virtualenvs/pywork/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/momo/.virtualenvs/pywork/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1075, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.


Thanks in advance

**Comment by steve21124** [comment]
:). same thing.

**Comment by zazizou** [comment]
Do you mean line 461 ?

`input_frame = cv2.imread(input_video)`

**Comment by ahmetozlu** [comment]
thanks for your support @finalwind !
