### ISSUE TITLE
 Attempted to use a closed Session.

### ISSUE THREAD

**Issue by KhalidAlmalki** [ahmetozlu/tensorflow_object_counting_api#50]
Hello There,

I'm trying to run the code at my end i got this error. how to fix it?

Traceback (most recent call last):
  File "/home/kjaf3f/Desktop/khalid/tensorflow_object_counting_api-master/single_image_object_counting.py", line 21, in <module>
    result = object_counting_api.single_image_object_counting(input_video, detection_graph, category_index, is_color_recognition_enabled) # targeted objects counting
  File "/home/kjaf3f/Desktop/khalid/tensorflow_object_counting_api-master/api/object_counting_api.py", line 511, in single_image_object_counting
    feed_dict={image_tensor: image_np_expanded})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1096, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

**Comment by LordKnish** [comment]
I am experiencing this problem when running the single image object counting .py without modification

Traceback (most recent call last):
  File "single_image_object_counting.py", line 21, in <module>
    result = object_counting_api.single_image_object_counting(input_video, detection_graph, category_index, is_color_recognition_enabled) # targeted objects counting
  File "B:\Tensorflow\models\research\object_detection\api\object_counting_api.py", line 511, in single_image_object_counting
    feed_dict={image_tensor: image_np_expanded})
  File "C:\Users\berni\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\berni\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1103, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

Tensorflow: 1.15
