### ISSUE TITLE
error occurred on  jetson nano

### ISSUE THREAD

**Issue by SaddamBInSyed** [ahmetozlu/tensorflow_object_counting_api#67]
@ahmetozlu 

thanks for your work.
when i run the  **python3 vehicle_counting.py**

then I am getting below error.
note:
numpy is update to date.

2020-02-11 22:07:29.569821: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
Traceback (most recent call last):
  File "vehicle_counting.py", line 12, in <module>
    from api import object_counting_api
  File "/home/svnano/machinelearning/tensorflow_object_counting_api/api/object_counting_api.py", line 11, in <module>
    from utils import visualization_utils as vis_util
  File "/home/svnano/machinelearning/tensorflow_object_counting_api/utils/visualization_utils.py", line 41, in <module>
    from utils.color_recognition_module import color_recognition_api
  File "/home/svnano/machinelearning/tensorflow_object_counting_api/utils/color_recognition_module/color_recognition_api.py", line 1, in <module>
    from utils.color_recognition_module import color_histogram_feature_extraction
  File "/home/svnano/machinelearning/tensorflow_object_counting_api/utils/color_recognition_module/color_histogram_feature_extraction.py", line 12, in <module>
    from scipy.stats import itemfreq
  File "/usr/lib/python3/dist-packages/scipy/stats/__init__.py", line 348, in <module>
    from .stats import *
  File "/usr/lib/python3/dist-packages/scipy/stats/stats.py", line 177, in <module>
    from . import distributions
  File "/usr/lib/python3/dist-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/usr/lib/python3/dist-packages/scipy/stats/_continuous_distns.py", line 15, in <module>
    from scipy._lib._numpy_compat import broadcast_to
  File "/usr/lib/python3/dist-packages/scipy/_lib/_numpy_compat.py", line 10, in <module>
    from numpy.testing.nosetester import import_nose
ModuleNotFoundError: No module named 'numpy.testing.nosetester'

please advise

**Comment by ahmetozlu** [comment]
Set numpy version to '1.17.0' and then try again please..
