### ISSUE TITLE
Error in object_tracking.py .... How to resolve it?

### ISSUE THREAD

**Issue by m8770224** [ahmetozlu/tensorflow_object_counting_api#84]
Traceback (most recent call last):
  File "C:/Users/Dell/Downloads/tensorflow_object_counting_api-master/object_tracking.py", line 24, in <module>
    processed_img = backbone.processor(img)
  File "C:\Users\Dell\Downloads\tensorflow_object_counting_api-master\backbone.py", line 70, in processor
    img_dim = (img.shape[1], img.shape[0])
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by ahmetozlu** [comment]
It seems that your input resource path is not valid or it is incorrect. Please check your input resource exact path on code and be sure about you set it correctly.

**Comment by m8770224** [comment]
Ok.  Thank you.
One more dout I have, would you please tell me how to reduce the width of
that roi line.
